### PR TITLE
remove "application android:label" from Manifest of library -> preven…

### PR DESCRIPTION
**Pull request by Rainer-Lang**
remove "application android:label" from Manifest of library -> prevent "Error: Manifest merger failed"

Is it possible to merge fast and make a new version?

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
Thanks a lot - and for your great lib too.

**Comment by Rainer-Lang** [comment]
@krimin-killr21 Version isn't populated. Can't get it.

**Comment by MFlisar** [comment]
you can always manually remove those things for the merger. Here's an example (it shows removing of some of the imported data like label, icon and theme):

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

     <application
        tools:replace="label,icon,theme" >

    </application>

</manifest>
```

**Comment by OunmanNgampeerapong** [comment]
Ok

**Pull request merged**
